### PR TITLE
Update fsevents fix for legacy macOS

### PR DESCRIPTION
**Pull request by barracuda156**
Probably switch to this version

### CODE REVIEW

**Comment by nlogozzo** [comment]
I've added the fix for what we talked about here: https://github.com/NickvisionApps/Parabolic/pull/953

**Comment by barracuda156** [comment]
Awesome!

**Review by nlogozzo — APPROVED** [review]

**Comment by nlogozzo** [comment]
https://github.com/NickvisionApps/libnick/releases/tag/2024.11.1

**Comment by barracuda156** [comment]
Great, I will update to this one now and drop patches.

**Pull request merged**
