### PR TITLE
Fix x86-windows by adding missing calling conventions.

### PR DESCRIPTION
**Pull request by BillyONeal**

### CODE REVIEW

**Comment by nlogozzo** [comment]
Thank you for the fixes!

**Review by nlogozzo — APPROVED** [review]

**Comment by nlogozzo** [comment]
@BillyONeal just a curiosity for learning sake, why are these needed for x86 and not x64?

**Comment by BillyONeal** [comment]
> @BillyONeal just a curiosity for learning sake, why are these needed for x86 and not x64?

Because x64 doesn't have `__cdecl` vs. `__stdcall` vs `__fastcall`.

For the window procedure one, the signature of the window procedure is documented to be:

```c++
LRESULT CALLBACK WindowProc(HWND hwnd, UINT uMsg, WPARAM wParam, LPARAM lParam);
```

In the modern era `CALLBACK` is normally `__stdcall`. But `__stdcall` doesn't mean anything on x64, so that the signature is 'incorrect' doesn't matter.

For the COM interfaces, that's similarly how they're declared, and in that case again that macro expands to `__stdcall`:

```c++
    MIDL_INTERFACE("00000000-0000-0000-C000-000000000046")
    IUnknown
    {
    public:
        BEGIN_INTERFACE
        virtual HRESULT STDMETHODCALLTYPE QueryInterface( 
            /* [in] */ const GUID *riid,
            /* [annotation][iid_is][out] */ 
            __RPC__deref_out  void **ppvObject) = 0;
        
        virtual ULONG STDMETHODCALLTYPE AddRef( void) = 0;
        
        virtual ULONG STDMETHODCALLTYPE Release( void) = 0;
        
        END_INTERFACE
    };
```

**Comment by nlogozzo** [comment]
Ah ok, got it...thanks!

**Pull request merged**
